import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next.js at build time.
 *
 * Allows search engines to index the marketing pages (/, /about, /signup,
 * /login, /forgot-password, /waitlist) but blocks crawlers from the
 * authenticated app surface and every API endpoint. That keeps the
 * dashboard / admin / billing / projects routes out of search results
 * (they require auth anyway, but pre-empts crawler hits and any leaked
 * preview-deploy URLs from being indexed).
 *
 * Points sitemap at https://projectoolbox.com/sitemap.xml — also
 * generated at build time by src/app/sitemap.ts.
 */
export default function robots(): MetadataRoute.Robots {
  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://projectoolbox.com";
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: [
          "/api/",
          "/dashboard",
          "/admin",
          "/projects",
          "/agents",
          "/portfolio",
          "/programmes",
          "/approvals",
          "/billing",
          "/calendar",
          "/knowledge",
          "/meetings",
          "/notifications",
          "/activity",
          "/invoices",
          "/ml-insights",
          "/sentiment",
          "/onboarding",
        ],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}