import type { MetadataRoute } from "next";

/**
 * sitemap.xml — generated by Next.js at build time.
 *
 * Lists the public marketing pages only. Authenticated routes
 * (/dashboard, /projects, /admin, …) are intentionally excluded —
 * they're behind auth and there's no public content for crawlers to
 * index. The robots.ts companion file blocks the same set defensively.
 *
 * Update the `routes` array if you add a new public page (e.g. /pricing,
 * /careers, blog posts). Don't list dynamic routes that need params.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://projectoolbox.com";
  const now = new Date();

  const routes: Array<{
    path: string;
    changeFrequency: "daily" | "weekly" | "monthly" | "yearly";
    priority: number;
  }> = [
    { path: "/",               changeFrequency: "weekly", priority: 1.0 },
    { path: "/about",          changeFrequency: "monthly", priority: 0.8 },
    { path: "/login",          changeFrequency: "yearly", priority: 0.3 },
    { path: "/signup",         changeFrequency: "yearly", priority: 0.6 },
    { path: "/waitlist",       changeFrequency: "yearly", priority: 0.5 },
    { path: "/forgot-password", changeFrequency: "yearly", priority: 0.2 },
  ];

  return routes.map(r => ({
    url: `${base}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}