import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { auth } from "@/lib/auth";

// GET /api/projects/:id/artefacts — List artefacts generated by the agent
export async function GET(_req: NextRequest, { params }: { params: Promise<{ projectId: string }> }) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { projectId } = await params;

  // AgentArtefact has no Prisma relation to Agent — join manually
  const artefacts = await db.agentArtefact.findMany({
    where: { projectId },
    orderBy: { createdAt: "desc" },
    select: {
      id: true, name: true, format: true, content: true,
      status: true, version: true, feedback: true,
      phaseId: true, createdAt: true, updatedAt: true,
      agentId: true,
    },
  });

  // Fetch unique agents referenced by these artefacts
  const agentIds = [...new Set(artefacts.map(a => a.agentId).filter(Boolean))];
  const agents = agentIds.length > 0
    ? await db.agent.findMany({
        where: { id: { in: agentIds } },
        select: { id: true, name: true, gradient: true },
      })
    : [];
  const agentMap = Object.fromEntries(agents.map(a => [a.id, a]));

  const enriched = artefacts.map(a => ({
    ...a,
    agent: agentMap[a.agentId] ?? null,
  }));

  return NextResponse.json({ data: enriched });
}
