import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { auth } from "@/lib/auth";

// GET /api/projects/:id/artefacts — List artefacts generated by the agent
export async function GET(_req: NextRequest, { params }: { params: Promise<{ projectId: string }> }) {
  const session = await auth();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { projectId } = await params;

  const artefacts = await db.agentArtefact.findMany({
    where: { projectId },
    orderBy: { createdAt: "desc" },
    select: {
      id: true, name: true, format: true, content: true,
      status: true, version: true, feedback: true,
      phaseId: true, createdAt: true, updatedAt: true,
    },
  });

  return NextResponse.json({ data: artefacts });
}
